### ISSUE TITLE
Broken CurrencyConverter: currency_huilv.js unavailable

### ISSUE THREAD

**Issue by syssi** [HerrHofrat/gearbest_parser#1]
```
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from gearbest_parser import GearbestParser, CurrencyConverter
>>> converter = CurrencyConverter()
>>> converter.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/gearbest_parser/gearbest_parser.py", line 59, in update
    page = urlopen(req).read().decode('utf-8')
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
>>> 
```

https://order.gearbest.com/data-cache/currency_huilv.js isn't available anymore.

Downstream issue: https://github.com/home-assistant/home-assistant/issues/14813

**Comment by milokmet** [comment]
converter.update() seems to be broken again :(

**Comment by HerrHofrat** [comment]
I'll try to find a solution that is more future proof - will take a while as I currently have no time to look at it..
